from PIL import ImageFont, ImageDraw, Image, ImageFilter
from Algorithm_colorMaterial import LIGHTorDARK

def drawCopyright(image = None,
                    subsFont = '/home/linkgish/Desktop/WebApp2/GeneticDesignProject/Font-lib/Muli/Muli-RegularItalic.ttf',   #Open custom font):
                    copyRight = 'Generated by AiDesign',
                    useOverlay = True,
        ):
    #Copyright    
    result_img = image 
    img_size = result_img.size[1]
    subs_font = ImageFont.truetype(subsFont,100)
    textSize = subs_font.getsize(copyRight)

    canvas = Image.new('RGBA', textSize)
    draw = ImageDraw.Draw(canvas)
    draw.text((0,0),copyRight, fill='white',font=subs_font)

    ratio = (result_img.size[1]/50)/textSize[1]
    newSize = int(textSize[0]*ratio), int(textSize[1]*ratio)
    
    # print(newSize)
    canvas = canvas.resize(newSize, Image.ANTIALIAS)
    
    # print(canvas)
    colorDominant = LIGHTorDARK(image=result_img,
                        posX=img_size*24//30,
                        posY=img_size*29//30,
                        sizeX=img_size*24//30+canvas.size[0],
                        sizeY=img_size*29//30+canvas.size[1])
    if (useOverlay==True):
        OverlayColor = Image.new('RGBA',canvas.size, color=colorDominant)
        canvas = Image.composite(OverlayColor, canvas, canvas)
        
        result_img.paste(canvas, (img_size*24//30,(img_size*29//30)), canvas )
        return result_img   
    else:
        result_img.paste(canvas, (img_size*24//30,(img_size*29//30)), canvas )
        return result_img   
    