# Generated by Django 2.2.2 on 2019-07-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artif_start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_title', models.CharField(max_length=200)),
                ('start_content', models.TextField()),
                ('start_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
